### PR TITLE
Add to switch between Logo and Wordmark

### PR DESCRIPTION
**Pull request by ridemountainpig**
Add feature: #128  

https://github.com/pheralb/svgl/assets/92412722/1a69fa22-7133-4dc2-9143-0b3668d97498

### CODE REVIEW

**Comment by ridemountainpig** [comment]
@pheralb how do you look. Thank you. 😊

**Comment by pheralb** [comment]
I like the idea 🫡🚀

**Comment by pheralb** [comment]
I will work on a bug to download also the ver. wordmark 👀

**Comment by pheralb** [comment]
Ready 🥳🚀
image

**Comment by ridemountainpig** [comment]
LGTM 😃 🥳

**Comment by davidho0403** [comment]
> @davidho0403 Is this feature what you had in mind? Thank you. 😊

Yah! Amazing work! 💯

**Pull request merged**
