### PR TITLE
🔒 Add Authentication category and `Clerk` logo

### LINKED ISSUE #468: [Request]: add Authentication category
## Description

**What is the issue?**  
Add `Authentication` category

---

## Steps to Reproduce
For new icons for auth libraries like Cleck, Auth0, Authjs... etc

---

## Expected Behavior

What should have happened instead of the issue?
There should be a `Authentication` category

---

### PR DESCRIPTION
**Pull request by ridemountainpig**
- Add Authentication category, closes #468
- Add `Clerk` logo SVG

### CODE REVIEW

**Comment by PsychoKillerdd** [comment]
Hello, I think they should put the old css logo back and also leave the new one

**Comment by pheralb** [comment]
Hi @ridemountainpig 🫡,

I like the idea of adding the category! But, please don't modify the original Clerk svg. Can you add the light/dark mode version? 🤔
- https://clerk.com/design

Thanks 🚀🚀

**Comment by pheralb** [comment]
> Hello, I think they should put the old css logo back and also leave the new one

I'll fix it 🫡

**Comment by ridemountainpig** [comment]
> Hi @ridemountainpig 🫡,
> 
> I like the idea of adding the category! But, please don't modify the original Clerk svg. Can you add the light/dark mode version? 🤔
> 
> * https://clerk.com/design
> 
> Thanks 🚀🚀

I have already updated the clerk SVG. Thanks, @pheralb! 🫡

**Comment by pheralb** [comment]
> > Hi @ridemountainpig 🫡,
> > I like the idea of adding the category! But, please don't modify the original Clerk svg. Can you add the light/dark mode version? 🤔
> > 
> > * https://clerk.com/design
> > 
> > Thanks 🚀🚀
> 
> I have already updated the clerk SVG. Thanks, @pheralb! 🫡

Thanks 🚀✨

**Comment by PsychoKillerdd** [comment]
> > Hello, I think they should put the old css logo back and also leave the new one
> 
> I'll fix it 🫡

thx bro i appreciate it , maybe a new category  "legancy"

**Comment by pheralb** [comment]
@PsychoKillerdd Ready 🫡
- Old: https://svgl.app/?search=css
- New: https://svgl.app/?search=css+%28new%29

**Comment by PsychoKillerdd** [comment]
thank you so much , for your time :) :) 👍

**Pull request merged**
